/**
 * @file registration.schema.ts
 * @description Schema for event registrations — the join between a
 * participant and an event.
 *
 * A registration is created when a participant submits a registration form
 * for a specific event. It is the most complex document in the system,
 * combining data from multiple sources into a single, self-contained record.
 *
 * Registration lifecycle (status field):
 *   pending    → just submitted; awaiting staff review
 *   approved   → reviewed and accepted; ticket is generated at this point
 *   rejected   → reviewed and declined; rejectionReason should be recorded
 *   checked_in → participant physically arrived and was scanned at the venue
 *
 * Key design decisions:
 *
 * 1. formSnapshot — the exact form structure (fields, labels, options) at
 *    submission time is frozen here. If the event organizer edits the form
 *    later, this registration still accurately reflects what the participant
 *    saw and filled in.
 *
 * 2. answers — self-describing answer objects (fieldId + key + label + type
 *    + value). Each answer can be read independently without joining to the
 *    form snapshot — important for analytics exports and audit logs.
 *
 * 3. Snapshot fields (companySnapshot, industrySnapshot, etc.) — copied from
 *    the participant's profile at submission time. If the participant updates
 *    their profile later, this registration still reflects the data that was
 *    accurate when they registered.
 *
 * 4. ticket — null until the registration is approved. Generated by the
 *    application layer upon approval. A unique QR code is assigned at that point.
 *
 * 5. checkIn — initialized with defaults at creation. Updated in-place when
 *    the participant is scanned at the venue.
 *
 * 6. One registration per participant per event — enforced by a unique
 *    compound index on { eventId, participantId }.
 */

import { Schema, model, Types } from "mongoose";
import { STATUS } from "../constants/enums.js"
import type { UserRole, RegistrationStatus } from "../constants/enums.js";
import { FormSnapshotFieldSchema } from "./sub/form-snapshot-field.schema.js";
import type { IFormSnapshotField } from "./sub/form-snapshot-field.schema.js";
import { RegistrationAnswerSchema } from "./sub/registration-answer.schema.js";
import type { IRegistrationAnswer } from "./sub/registration-answer.schema.js";
import { CompanySnapshotSchema } from "./sub/company-snapshot.schema.js";
import type { ICompanySnapshot } from "./sub/company-snapshot.schema.js";
import { MasterSnapshotSchema } from "./sub/master-snapshot.schema.js";
import type { IMasterSnapshot } from "./sub/master-snapshot.schema.js";
import { TicketSchema } from "./sub/ticket.schema.js";
import type { ITicket } from "./sub/ticket.schema.js";
import { CheckInSummarySchema } from "./sub/checkin-summary.schema.js";
import type { ICheckInSummary } from "./sub/checkin-summary.schema.js";

export interface IRegistration {
  /** Reference to the event this registration belongs to. */
  eventId: Types.ObjectId;

  /** Reference to the participant who submitted this registration. */
  participantId: Types.ObjectId;

  /**
   * The role of the participant at this specific event.
   * Only "participant" or "exhibitor" should be written here.
   * Application layer enforces this — schema allows all USER_ROLE values.
   */
  participantType: UserRole;

  /** Current lifecycle status of this registration. */
  status: RegistrationStatus;

  /** Approval/rejection metadata populated when the registration is reviewed. */
  approval: {
    /** The staff member who approved this registration. Null if not yet approved. */
    approvedBy: Types.ObjectId | null;
    /** Timestamp of approval. Null if not yet approved. */
    approvedAt: Date | null;
    /** The staff member who rejected this registration. Null if not rejected. */
    rejectedBy: Types.ObjectId | null;
    /** Timestamp of rejection. Null if not rejected. */
    rejectedAt: Date | null;
    /** Reason for rejection. Should always be set when status is "rejected". */
    rejectionReason: string | null;
  };

  /**
   * Frozen snapshot of the registration form at the time of submission.
   * Immutable after creation — never updated even if the event form changes.
   */
  formSnapshot: {
    /** The form version number at the time of submission. */
    version: number;
    /** The field definitions exactly as the participant saw them. */
    fields: IFormSnapshotField[];
  };

  /**
   * The participant's submitted answers, one per form field.
   * Self-describing — each answer carries its own field metadata.
   */
  answers: IRegistrationAnswer[];

  /** Company snapshot copied from the participant's profile at submission time. */
  companySnapshot: ICompanySnapshot;

  /** Industry snapshot copied from the participant's profile at submission time. */
  industrySnapshot: IMasterSnapshot;

  /** Job title snapshot copied from the participant's profile at submission time. */
  jobTitleSnapshot: IMasterSnapshot;

  /** City snapshot copied from the participant's profile at submission time. */
  citySnapshot: IMasterSnapshot;

  /**
   * The QR code ticket issued to this participant after approval.
   * Null until the registration status transitions to "approved".
   * Application layer generates and populates this on approval.
   */
  ticket: ITicket | null;

  /**
   * Check-in summary for this registration.
   * Initialized with defaults (isAttended: false) at creation.
   * Updated in-place when the participant arrives at the venue.
   */
  checkIn: ICheckInSummary;
}

const RegistrationSchema = new Schema<IRegistration>(
  {
    eventId: {
      type: Schema.Types.ObjectId,
      ref: "Event",
      required: true,
    },
    participantId: {
      type: Schema.Types.ObjectId,
      ref: "Participant",
      required: true,
    },
    participantType: {
      type: String,
      required: true,
      enum: STATUS.USER_ROLE,
    },
    status: {
      type: String,
      required: true,
      enum: STATUS.REGISTRATION,
      default: "pending",
    },
    approval: {
      approvedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },
      approvedAt: { type: Date, default: null },
      rejectedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },
      rejectedAt: { type: Date, default: null },
      rejectionReason: { type: String, trim: true, default: null },
    },
    formSnapshot: {
      version: { type: Number, required: true, default: 1 },
      fields: {
        type: [FormSnapshotFieldSchema],
        required: true,
        default: [],
      },
    },
    answers: {
      type: [RegistrationAnswerSchema],
      required: true,
      default: [],
    },
    companySnapshot: {
      type: CompanySnapshotSchema,
      default: () => ({}),
    },
    industrySnapshot: {
      type: MasterSnapshotSchema,
      default: () => ({}),
    },
    jobTitleSnapshot: {
      type: MasterSnapshotSchema,
      default: () => ({}),
    },
    citySnapshot: {
      type: MasterSnapshotSchema,
      default: () => ({}),
    },
    // Fix from schema review: changed from required:true to default:null.
    // Tickets are only generated after approval — a pending registration
    // must not have a ticket.
    ticket: {
      type: TicketSchema,
      default: null,
    },
    checkIn: {
      type: CheckInSummarySchema,
      default: () => ({}),
    },
  },
  {
    timestamps: true,
    collection: "registrations",
  }
);

// --- Indexes ---

// Business rule: one participant cannot register for the same event twice.
RegistrationSchema.index({ eventId: 1, participantId: 1 }, { unique: true });

// Primary query for event management — "show all pending registrations for event X".
RegistrationSchema.index({ eventId: 1, status: 1 });

// Participant history — "show all events this participant has registered for".
RegistrationSchema.index({ participantId: 1, createdAt: -1 });

// Role-based filtering within an event — "show all exhibitors for event X".
RegistrationSchema.index({ eventId: 1, participantType: 1 });

// Analytics — filter registrations by company, industry, or city.
RegistrationSchema.index({ "companySnapshot.companyId": 1 });
RegistrationSchema.index({ "industrySnapshot.refId": 1 });
RegistrationSchema.index({ "citySnapshot.refId": 1 });

// Check-in scanner lookup — must be fast; unique ensures no two registrations
// share the same QR code (enforced both here and by ticket generation logic).
RegistrationSchema.index({ "ticket.qrCode": 1 }, { unique: true, sparse: true });

// Organization name search — supports regex search across registrations without
// joining to the Participant collection. Added for the participant management list.
RegistrationSchema.index({ "companySnapshot.name": 1 });

export const Registration = model<IRegistration>("Registration", RegistrationSchema);